#!/data/data/com.termux/files/usr/bin/bash
abang='\033[1;31m'
ijo='\033[1;32m'
biru='\033[1;34m'
pkg install python2 nano
clear
echo -n "Waiting Data!!!"
sleep 3
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo -e "$abang Menginstall Terlogin"
sleep 0.1
clear
echo -e "$ijo Menginstall Terlogin"
sleep 0.1
clear
echo -e "$biru Menginstall Terlogin"
sleep 0.1
clear
echo ""
echo -n -e """$ijo silahkan Ganti password nya !!!
$abang
\t\tPERHATIAN !!!
$ijo
Dilarang mengubah code tanpa ijin
jika sudah mengerti silahkan lanjut $biru[ENTER]"""
read perhatian
mkdir /data/data/com.termux/files/home/.terlogin
mv bin/login.py /data/data/com.termux/files/home/.terlogin
rm -rf bin
echo """
clear
python2 /data/data/com.termux/files/home/.terlogin/login.py
""" >> /data/data/com.termux/files/usr/etc/bash.bashrc
nano /data/data/com.termux/files/home/.terlogin/login.py

echo -e "\n\033[1;32m## Thanks For Using Terlogin ##"
echo -e "\nsilahkan mulai ulang termux\n"
echo ""
sleep 10
