#!/bin/bash
echo -e "\033[1;32m [ UNINSTALL TERLOGIN ] \033[0m"
sleep 4
rm -rf ../.terlogin
rm -rf /data/data/com.termux/files/home/terlogin
echo """
command_not_found_handle() {
		/data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}
""" > ../../usr/etc/bash.bashrc
echo -e "\033[1;32m [ CLEAR ] \033[0m"
